# site settings
title: IB Repository
subtitle: by jingying
email: jingyingwjy@gmail.com
description: Many IB Notes.
baseurl: "/ibrepository" # the subpath of your site, e.g. /blog
url: "https://jingyingwang.github.io/" 
author: Jingying
street_address: 1234 Somewhere Road
city: city
state: Place
zip_code: 55555
country: Country
phone: 000000000

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 8

# social settings
500px_url:
facebook_url:
github_url: https://github.com/jingyingwang
gitlab_url: 
googleplus_url: 
instagram_url: 
linkedin_url: 
pinterest_url:
slack_url:
twitter_url: 

# build settings
markdown: kramdown

sass:
  style: compressed
